blank_issues_enabled: true
contact_links:
  - name: Commercial licensing or written permissions
    url: https://github.com/GnollStack/The-Sound-of-Silence
    about: Please contact GnollStack directly by Discord or email for commercial licensing or written permission requests.
